import { useState, useMemo } from "react";
import type { CalendarEvent, CalendarStore, MonthCell, PickerCell, RepeatEnds, RepeatFreq } from "./types";
import { EVENT_COLORS, MONTHS } from "./mockData";

/**
 * Builds the month grid: leading `null`s pad the week before the 1st, and
 * trailing `null`s complete the final week.
 */
export function buildCalendar(year: number, month: number): MonthCell[] {
  const firstDay = new Date(year, month, 1).getDay();
  const daysInMonth = new Date(year, month + 1, 0).getDate();
  const cells: MonthCell[] = Array(firstDay).fill(null);

  for (let d = 1; d <= daysInMonth; d++) cells.push(d);
  while (cells.length % 7 !== 0) cells.push(null);

  return cells;
}

/**
 * Builds the date-picker grid. Unlike `buildCalendar` the padding cells carry
 * real dates from the neighbouring months so they can still be selected.
 */
export function buildFullCalendar(month: number, year: number): PickerCell[] {
  const firstDay = new Date(year, month, 1).getDay();
  const daysInCur = new Date(year, month + 1, 0).getDate();
  const prevMonth = month === 0 ? 11 : month - 1;
  const prevYear = month === 0 ? year - 1 : year;
  const daysInPrev = new Date(prevYear, prevMonth + 1, 0).getDate();
  const nextMonth = month === 11 ? 0 : month + 1;
  const nextYear = month === 11 ? year + 1 : year;

  const cells: PickerCell[] = [];

  for (let i = firstDay - 1; i >= 0; i--) cells.push({ day: daysInPrev - i, month: prevMonth, year: prevYear, current: false });
  for (let d = 1; d <= daysInCur; d++) cells.push({ day: d, month, year, current: true });

  let nd = 1;
  while (cells.length % 7 !== 0) cells.push({ day: nd++, month: nextMonth, year: nextYear, current: false });

  return cells;
}

/**
 * `useCalendarEvents` controls the event list, including:
 * - `events`: every event across all months
 * - `addEvent()`: add a new event
 * - `removeEvent()`: remove an event by id
 */
export function useCalendarEvents(initial: CalendarEvent[]): CalendarStore {
  const [events, setEvents] = useState<CalendarEvent[]>(initial);

  /** Adds a new event. The object has no id because the id is generated by the database */
  function addEvent(event: Omit<CalendarEvent, "id">) {
    if (!event.title.trim()) return;

    setEvents((es) => [...es, { id: Date.now(), ...event }]);
  }

  function removeEvent(id: number) {
    setEvents((es) => es.filter((e) => e.id !== id));
  }

  return { events, addEvent, removeEvent };
}

/**
 * `useCalendarView` manages which month the grid is showing and which day is
 * selected, including:
 * - `cells`: the month grid for the viewed month
 * - `prevMonth()` / `nextMonth()`: step the viewed month
 * - `selectDay()`: select a day, or clear it by selecting it again
 */
export function useCalendarView() {
  const today = new Date();
  const [viewYear, setViewYear] = useState(today.getFullYear());
  const [viewMonth, setViewMonth] = useState(today.getMonth());
  const [selectedDay, setSelectedDay] = useState<number | null>(today.getDate());

  const cells = useMemo(() => buildCalendar(viewYear, viewMonth), [viewYear, viewMonth]);
  const isCurrentMonth = viewYear === today.getFullYear() && viewMonth === today.getMonth();

  function prevMonth() {
    if (viewMonth === 0) {
      setViewMonth(11);
      setViewYear((y) => y - 1);
    } else {
      setViewMonth((m) => m - 1);
    }
    setSelectedDay(null);
  }

  function nextMonth() {
    if (viewMonth === 11) {
      setViewMonth(0);
      setViewYear((y) => y + 1);
    } else {
      setViewMonth((m) => m + 1);
    }
    setSelectedDay(null);
  }

  /** Selects a day, or clears the selection when the selected day is clicked again */
  function selectDay(day: number) {
    setSelectedDay((d) => (d === day ? null : day));
  }

  return { viewYear, viewMonth, selectedDay, selectDay, setSelectedDay, prevMonth, nextMonth, cells, isCurrentMonth, today };
}

/**
 * `useNewEventForm` controls the input fields for a new event, including:
 * - `title`: the event's description
 * - start / end date and time
 * - `color`: one of `EVENT_COLORS`
 * - `shareWith`: a teammate the event is also added for (empty when private)
 * - repeat settings (frequency, and whether/when the repetition ends)
 * - `reset()`: clear the input
 * - `buildEvent()`: create a `CalendarEvent` with no id
 */
export function useNewEventForm() {
  const today = new Date();

  const [title, setTitle] = useState("");
  const [color, setColor] = useState<string>(EVENT_COLORS[0]);
  const [shareWith, setShareWith] = useState("");

  const [startMonth, setStartMonth] = useState(today.getMonth());
  const [startDay, setStartDay] = useState(today.getDate());
  const [startYear, setStartYear] = useState(today.getFullYear());
  const [startTime, setStartTime] = useState("9:00 AM");

  const [endMonth, setEndMonth] = useState(today.getMonth());
  const [endDay, setEndDay] = useState(today.getDate());
  const [endYear, setEndYear] = useState(today.getFullYear());
  const [endTime, setEndTime] = useState("9:30 AM");

  const [repeat, setRepeat] = useState(false);
  const [repeatFreq, setRepeatFreq] = useState<RepeatFreq>("weekly");
  const [repeatEnds, setRepeatEnds] = useState<RepeatEnds>("never");
  const [repeatCount, setRepeatCount] = useState(4);
  const [repeatEndMonth, setRepeatEndMonth] = useState(today.getMonth());
  const [repeatEndDay, setRepeatEndDay] = useState(today.getDate());
  const [repeatEndYear, setRepeatEndYear] = useState(today.getFullYear());

  /** Points the form at a specific day, used when the user adds from a selected day */
  function openOn(month: number, day: number, year: number) {
    setStartMonth(month);
    setStartDay(day);
    setStartYear(year);
    setEndMonth(month);
    setEndDay(day);
    setEndYear(year);
  }

  function reset() {
    setTitle("");
    setShareWith("");
    setRepeat(false);
  }

  /**
   * Creates the `CalendarEvent` with no id.
   * The time range and repeat frequency are folded into the title, which is
   * what the event row renders.
   */
  function buildEvent(): Omit<CalendarEvent, "id"> | null {
    if (!title.trim()) return null;

    const sameDay = endDay === startDay && endMonth === startMonth && endYear === startYear;
    const timeRange = sameDay
      ? `${startTime} – ${endTime}`
      : `${startTime} – ${MONTHS[endMonth]} ${endDay}, ${endTime}`;
    const repeatLabel = repeat ? ` · ${repeatFreq.charAt(0).toUpperCase() + repeatFreq.slice(1)}` : "";

    return {
      day: startDay,
      month: startMonth,
      year: startYear,
      title: `${title.trim()} — ${timeRange}${repeatLabel}`,
      color,
    };
  }

  return {
    title, setTitle,
    color, setColor,
    shareWith, setShareWith,
    startMonth, setStartMonth, startDay, setStartDay, startYear, setStartYear, startTime, setStartTime,
    endMonth, setEndMonth, endDay, setEndDay, endYear, setEndYear, endTime, setEndTime,
    repeat, setRepeat,
    repeatFreq, setRepeatFreq,
    repeatEnds, setRepeatEnds,
    repeatCount, setRepeatCount,
    repeatEndMonth, setRepeatEndMonth, repeatEndDay, setRepeatEndDay, repeatEndYear, setRepeatEndYear,
    openOn, reset, buildEvent,
  };
}
