import { useState, useMemo } from "react";
import type { FilterConfig, Todo, TodoStore } from "./types";
import type { AssignMode, TodoFilter } from "./types";

/**
 * `useTodos` controls to-do list state, including:
 * - `todos`: to-do list
 * - `addTodo()`: add new to-do task
 * - `removeCompletedTodos()` :remove completed to-do
 * - `toggle()`: toggle complete/incomplete to-do task
 */
export function useTodos(initial: Todo[]): TodoStore {
  const [todos, setTodos] = useState<Todo[]>(initial);

  /**
   * Toggles complete/incomplete given `id`
   */
  function toggle(id: number) {
    setTodos(tasks => tasks.map(task => task.id == id ? { ...task, done: !task.done } : task));
  }

  /** Adds new todo given the `Todo` object
   * - The object does not include id because the id is generated by the database 
   */
  function addTodo(todo: Omit<Todo, "id">) {
    if (!todo.text.trim()) return;

    setTodos(tasks => [...tasks, { id: Date.now(), ...todo }]);
  }

  function removeCompletedTodos() {
    setTodos(tasks => tasks.filter(t => !t.done));
  }

  return { todos, toggle, addTodo, removeCompletedTodos };
}

/**
 * `useNewTodoForm` controls the input field for new to-do task, include
 * - `text`: task's description
 * - `priority`: "low" | "medium" | "high"
 * - `assignMode`: "self" | "delegate"
 * - `delegateTo`: task's assignee in the team (empty if the `assignMode == "self"`)
 * - `customDelegate`: task's assignee outside the team (empty if the `assignMode == "self"`)
 * - `reset()`: clear the input
 * - `buildTodo()`: create `Todo` object with no id
 */
export function useNewTodoForm(authUser: string) {
  const [text, setText] = useState("")
  const [priority, setPriority] = useState<"low" | "medium" | "high">("medium")
  const [assignMode, setAssignMode] = useState<AssignMode>("self")
  const [delegateTo, setDelegateTo] = useState("")
  const [customDelegate, setCustomDelegate] = useState("")

  function reset() {
    setText("");
    setDelegateTo("");
    setCustomDelegate("");
  }

  function buildTodo(): Omit<Todo, "id"> | null {
    if (!text.trim()) return null;

    const resolveAssignee = (assignMode == "self" ? authUser : (delegateTo === "__custom__" ? customDelegate.trim() : delegateTo)) || authUser

    return {
      text: text.trim(),
      done: false,
      author: authUser,
      assignee: resolveAssignee,
      priority,
      delegated: resolveAssignee !== authUser
    }
  }

  return {
    text, setText,
    priority, setPriority,
    assignMode, setAssignMode,
    delegateTo, setDelegateTo,
    customDelegate, setCustomDelegate,
    reset, buildTodo
  }
}

/**
 * `useTodoFilter` manages filter system, including:
 * - `filter`: "done" | "all" | "mine" | "delegate-out"
 * - `filteredTodos`: filtered to-do list
 * - `filterConfig`: contains the filter's label, with its statistics summaries
 */
export function useTodoFilter(todos: Todo[], authUser: string) {
  const [filter, setFilter] = useState<TodoFilter>("all")

  const filteredTodos = useMemo(() => {
    if (filter === "mine") return todos.filter(t => !t.done && t.assignee === authUser)
    if (filter === "delegated-out") return todos.filter(t => !t.done && t.author === authUser && t.assignee !== authUser)
    if (filter === "done") return todos.filter(t => t.done)
    return todos.filter(t => !t.done || filter === "all")
  }, [todos, filter])

  const mineCount = todos.filter(t => !t.done && t.assignee === authUser).length
  const delegatedCount = todos.filter(t => !t.done && t.author === authUser && t.assignee !== authUser).length

  const filterConfigs: FilterConfig[] = [
    { id: "all", label: "All" },
    { id: "mine", label: "Mine", count: mineCount },
    { id: "delegated-out", label: "Delegated", count: delegatedCount },
    { id: "done", label: "Done" },
  ]

  return { filter, setFilter, filteredTodos, filterConfigs }
}